### ISSUE TITLE
How use pfix-srsd with multiple domains?

### ISSUE THREAD

**Issue by fluo75** [Fruneau/pfixtools#6]
Bonjour ;)

Thanks for this great tool.
Is it possible to use pfix-srsd with many domains? 
For example, set more than one domain in /etc/default/pfix-srsd?

Regards,

David

**Comment by hheimbuerger** [comment]
@ingenium13 @fluo75 If you have actually managed to implement this, I would be very thankful if you could share your configuration! Thanks!

**Comment by hheimbuerger** [comment]
@Fruneau Actually… is the FQDN that pfix-srsd expects as an argument the recipient domain (of the address to be rewritten, of which there could be multiple in a single postfix instance) or the mail server's hostname ([myhostname in the postfix config](http://www.postfix.org/postconf.5.html#myhostname))?

**Comment by Fruneau** [comment]
@hheimbuerger this is the domain used for SRS encoded addresses. This will be the domain of the envelop from of every outgoing email after SRS encoding.

**Comment by hheimbuerger** [comment]
@Fruneau So that is actually a problem then, if you want to forward mail from multiple different domains on the same mail server with pfix-srsd.

**Comment by Fruneau** [comment]
@hheimbuerger can you describe your use case?

**Comment by hheimbuerger** [comment]
@Fruneau I'm running a mail server (currently [adaline/dockermail](https://github.com/adaline/dockermail)) which receives mail on three different domains (i.e. which is the MX for three different domains). It hosts no actual mailboxes, but rather redirects/forwards all incoming mail to Gmail.

Right now, this setup fails a lot of SPF checks in Gmail and Gmail complains a lot. It is my (limited) understanding that implementing SRS should improve this situation a bit.

I've managed to [integrate pfix-srsd into this setup](https://github.com/hheimbuerger/dockermail/commit/c000cdd82681dc28372174d8e5750791b058ff90), but I don't yet understand which of my three domains I have to pass as the [domain](https://github.com/Fruneau/pfixtools/blob/master/pfix-srsd/pfix-srsd.asciidoc#mandatory-arguments) argument when running pfix-srsd.

**Comment by Fruneau** [comment]
@hheimbuerger you have to create a new domain or subdomain dedicated to SRS (something like "srs.yourdomain.com" or "bounces.yourdomain.com").

That domain you chose must be a dedicated one because you need to identify bounces coming back from the destination server and being able to route them to the SRS decoder in order to get back the original sender and thus forward the bounce back to the right user.

Moreover, that domain must be allowed as the output of your server so that gmail won't fail while checking SPF (I would highly advice adding a strict SPF rule on your SRS domain, this would ensure nobody else will try using that domain).

I hope this was clear enough.
